openapi: 3.0.1
info:
  title: SGM - Sistema de Gerenciamento para Marmitaria API
  version: v1
paths: {}
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
servers:
  - url: http://localhost:3000
